Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Document Name','Document Code','Document Type','Number','Risk');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Oak House Production Facility Code of Practice','COP','Code of Practice','CO-PRD1-COP-003','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Control Laboratory Code of Practice','COP','Code of Practice','CO-QC-COP-001','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','COP','Code of Practice','CO-QC-COP-002','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Verification and Validation','POL','Policy','CO-CA-POL-009','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Customer Feedback and Device Vigilance','POL','Policy','CO-CS-POL-012','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Training Policy','POL','Policy','CO-HR-POL-007','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Access Control Policy','POL','Policy','CO-IT-POL-022','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Asset Management Policy','POL','Policy','CO-IT-POL-023','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Business Continuity and Disaster Recovery','POL','Policy','CO-IT-POL-024','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Code of Conduct','POL','Policy','CO-IT-POL-025','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Cryptography Policy','POL','Policy','CO-IT-POL-026','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Human Resource Security Policy','POL','Policy','CO-IT-POL-027','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Information Security Policy','POL','Policy','CO-IT-POL-028','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Information Security Roles and Responsibilities','POL','Policy','CO-IT-POL-029','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Physical Security Policy','POL','Policy','CO-IT-POL-030','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Responsible Disclosure Policy','POL','Policy','CO-IT-POL-031','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Risk Management ','POL','Policy','CO-IT-POL-032','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Third Party Management','POL','Policy','CO-IT-POL-033','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Purchasing and Management of Suppliers','POL','Policy','CO-OPS-POL-008','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('WEEE Policy','POL','Policy','CO-OPS-POL-011','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reagent Production Policy','POL','Policy','CO-PRD1-POL-016','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Document Control and Change Management','POL','Policy','CO-QA-POL-006','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Control of Infrastructure Environment and Equipment','POL','Policy','CO-QA-POL-010','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for Complaints and Vigilance','POL','Policy','CO-QA-POL-013','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Poilcy for Control of Non Conformance ','POL','Policy','CO-QA-POL-014','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Policy for the use of Electronic Signatures within binx health','POL','Policy','CO-QA-POL-015','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Policy','POL','Policy','CO-QA-POL-019','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Risk Management Policy','POL','Policy','CO-QA-POL-020','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Manual','POL','Policy','CO-QA-POL-021','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Control Policy','POL','Policy','CO-QC-POL-018','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values (' Policy for Customer Interface  Order Handling  Product Storage & Distribution ','POL','Policy','CO-SUP-POL-017','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Supply Team Policy for Oak House Production Suite Operations','POL','Policy','CO-SUP-POL-034','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-001','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-002','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-003','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-004','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-005','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-006','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-007','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-DES-PTL-008','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-LAB-PTL-045','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-LAB-PTL-046','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-LAB-PTL-047','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-LAB-PTL-186','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-009','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-010','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-011','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-013','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-014','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-015','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-017','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-018','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-019','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-020','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-021','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-022','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-023','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-024','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-025','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-026','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-027','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-028','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-029','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-030','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-031','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-036','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-037','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-038','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-039','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-040','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-043','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('IO Release Procedure for Refurbished and Reworked Readers','PTL','Protocol','CO-OPS-PTL-048','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-049','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-050','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-OPS-PTL-051','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-075','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-078','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-086','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-087','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-088','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-089','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-090','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-091','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-092','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-093','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-094','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-095','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-096','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-097','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-098','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-099','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-100','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-101','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-102','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-103','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-104','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-105','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-PRD1-PTL-106','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-016','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-060','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-061','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-062','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-064','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-065','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-066','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-067','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-068','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-069','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-070','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-071','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-072','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-073','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-074','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','PTL','Protocol','CO-QC-PTL-077','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('CT Plasmid Quantification - qPCR Test (Part No. 0348)','QCP','Quality Control Protocol','CO-QC-QCP-055','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('ct/ng Collection Kit Batch Release','QCP','Quality Control Protocol','CO-QC-QCP-059','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('CT/NG Relabelled cartridge release procedure','QCP','Quality Control Protocol','CO-QC-QCP-060','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG TaqUNG Reagent Revision 1','QCP','Quality Control Protocol','CO-QC-QCP-068','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG CT-IC Detection Reagent Revision 2','QCP','Quality Control Protocol','CO-QC-QCP-065','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG CTIC Primer Passivation Reagent Revision 1','QCP','Quality Control Protocol','CO-QC-QCP-067','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('IC DNA in TE Buffer - Raw Material qPCR test','QCP','Quality Control Protocol','CO-QC-QCP-052','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG IC DNA Formulation','QCP','Quality Control Protocol','CO-QC-QCP-069','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG NG1-IC Detection Reagent Revision 2','QCP','Quality Control Protocol','CO-QC-QCP-064','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG NGIC Primer Passivation Reagent Revision 1','QCP','Quality Control Protocol','CO-QC-QCP-066','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QCP For CTNG NG2-IC Detection Reagent Revision 2','QCP','Quality Control Protocol','CO-QC-QCP-063','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values (' CTNG CTIC  NG1IC and NG2IC Detection Reagents QC test ','QCP','Quality Control Protocol','CO-QC-QCP-057','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Electrode testing','QCP','Quality Control Protocol','CO-QC-QCP-061','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Taq-B raw material','QCP','Quality Control Protocol','CO-QC-QCP-071','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Material Electrochemical Signal Interference test','QCP','Quality Control Protocol','CO-QC-QCP-058','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('NG1 Plasmid Quantification - qPCR Test (Part No. 0346)','QCP','Quality Control Protocol','CO-QC-QCP-054','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('NG2 Plasmid Quantification - qPCR Test (Part No. 0347','QCP','Quality Control Protocol','CO-QC-QCP-053','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QC release procedure for the Io Reader','QCP','Quality Control Protocol','CO-QC-QCP-062','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('CTNG Cartridge QCP ','QCP','Quality Control Protocol','CO-QC-QCP-056','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('T7 Exonuclease','QCP','Quality Control Protocol','CO-QC-QCP-039','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Enzymatics UNG 50U/uL QCP','QCP','Quality Control Protocol','CO-QC-QCP-070','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Collection of Human samples for QA purposes','SOP','Standard Operating Procedure','CO-CA-SOP-081','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procedure for Customer Service','SOP','Standard Operating Procedure','CO-CS-SOP-248','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('io Insepction using Data Collection Cartridge','SOP','Standard Operating Procedure','CO-CS-SOP-249','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Software Development Procedure','SOP','Standard Operating Procedure','CO-DES-SOP-004','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-DES-SOP-005','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-DES-SOP-006','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Design and Development Procedure','SOP','Standard Operating Procedure','CO-DES-SOP-029','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Design Review Work Instruction','SOP','Standard Operating Procedure','CO-DES-SOP-041','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Creation and maintenance of a Device Master Record','SOP','Standard Operating Procedure','CO-DES-SOP-042','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('CE Mark/Technical File Procedure','SOP','Standard Operating Procedure','CO-DES-SOP-243','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('IT Management Back Up and Support','SOP','Standard Operating Procedure','CO-IT-SOP-044','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Agilent Bioanalyzer SOP for RNA 6000 Pico and Nano Kits','SOP','Standard Operating Procedure','CO-LAB-SOP-002','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Validation of Temperature Controlled Equipemnt','SOP','Standard Operating Procedure','CO-LAB-SOP-003','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Bolt Mini Gel Tank for protein Electrophoresis','SOP','Standard Operating Procedure','CO-LAB-SOP-004','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Rhychiger Heat Sealer','SOP','Standard Operating Procedure','CO-LAB-SOP-005','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Esco Laminar Flow Cabinet','SOP','Standard Operating Procedure','CO-LAB-SOP-006','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reagent Deposition and Immobilisation (Pilot Line)','SOP','Standard Operating Procedure','CO-LAB-SOP-010','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Eppendorf 5424 Centrifuge','SOP','Standard Operating Procedure','CO-LAB-SOP-011','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Binder KBF-115 Oven','SOP','Standard Operating Procedure','CO-LAB-SOP-012','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Balance calibration','SOP','Standard Operating Procedure','CO-LAB-SOP-013','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Thermo Orion Star pH meter','SOP','Standard Operating Procedure','CO-LAB-SOP-014','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the ALC PK121 centrifuges (refrigerated and non-refrigrated)','SOP','Standard Operating Procedure','CO-LAB-SOP-015','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Peqlab thermal cyclers','SOP','Standard Operating Procedure','CO-LAB-SOP-016','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-017','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('LMS Programmable Incubator','SOP','Standard Operating Procedure','CO-LAB-SOP-019','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Hulme Martin Impulse Sealer in DNA free','SOP','Standard Operating Procedure','CO-LAB-SOP-020','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-022','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation of Bacterial Stocks','SOP','Standard Operating Procedure','CO-LAB-SOP-078','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use and cleaning of the ClassII Microbiology Safety Cabinet','SOP','Standard Operating Procedure','CO-LAB-SOP-079','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Agilent Bioanalyzer SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-080','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Rotary Vane Anemometer','SOP','Standard Operating Procedure','CO-LAB-SOP-082','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('External and repair Cleaning for io readers used at Atlas','SOP','Standard Operating Procedure','CO-LAB-SOP-095','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Temperature monitoring SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-097','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Grant XB2 Ultrasonic Bath','SOP','Standard Operating Procedure','CO-LAB-SOP-102','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Environmental Control in the Laboratory','SOP','Standard Operating Procedure','CO-LAB-SOP-103','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Laboratory cleaning SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-108','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Operation of the Prior Autoclave','SOP','Standard Operating Procedure','CO-LAB-SOP-129','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Heat Detection Rig Work Instructions','SOP','Standard Operating Procedure','CO-LAB-SOP-130','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Pipette Use and Calibration','SOP','Standard Operating Procedure','CO-LAB-SOP-131','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use and Completion of MFG documents','SOP','Standard Operating Procedure','CO-LAB-SOP-135','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Solution preparation SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-136','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Monitoring Variable Temperature Apparatus','SOP','Standard Operating Procedure','CO-LAB-SOP-137','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of temperature and humidity loggers','SOP','Standard Operating Procedure','CO-LAB-SOP-138','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Storage and Safe handling of Biohazardous Materials','SOP','Standard Operating Procedure','CO-LAB-SOP-145','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reagent Aliquot SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-148','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Introducing New Laboratory Equipment','SOP','Standard Operating Procedure','CO-LAB-SOP-149','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('-80 Freezer Temperature Monitoring','SOP','Standard Operating Procedure','CO-LAB-SOP-150','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Management and Control of Critical and Controlled equipment','SOP','Standard Operating Procedure','CO-LAB-SOP-151','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reporting & Recording Instrument Failures ','SOP','Standard Operating Procedure','CO-LAB-SOP-152','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of UV cabinets','SOP','Standard Operating Procedure','CO-LAB-SOP-153','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Lab book write up','SOP','Standard Operating Procedure','CO-LAB-SOP-155','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Lab rough notes','SOP','Standard Operating Procedure','CO-LAB-SOP-156','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of NanoDrop SP2000 Spectrophotometer for quantifying nucleic acid and protein samples','SOP','Standard Operating Procedure','CO-LAB-SOP-158','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Rotorgene Q','SOP','Standard Operating Procedure','CO-LAB-SOP-159','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-160','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-161','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Running End to End CT cartridges on io Readers','SOP','Standard Operating Procedure','CO-LAB-SOP-163','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Operation and Maintenance of HT24-2P Bambi Compressor and DSIS Sealer','SOP','Standard Operating Procedure','CO-LAB-SOP-164','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Attaching Electrode/Blister Adhesive and Blister Pack','SOP','Standard Operating Procedure','CO-LAB-SOP-167','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Janway 3510 model pH Meter','SOP','Standard Operating Procedure','CO-LAB-SOP-168','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Fermant Pouch Sealer (Pilot Line)','SOP','Standard Operating Procedure','CO-LAB-SOP-169','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Rapid PCR Rig Work Instructions','SOP','Standard Operating Procedure','CO-LAB-SOP-170','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Out of Hours Temperature Monitoring ','SOP','Standard Operating Procedure','CO-LAB-SOP-175','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('SOP to provide guidance for IQC's','SOP','Standard Operating Procedure','CO-LAB-SOP-176','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QuantStudio 3D digital PCR System','SOP','Standard Operating Procedure','CO-LAB-SOP-177','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Signal Analyser','SOP','Standard Operating Procedure','CO-LAB-SOP-178','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Cleaning Procedure for Microbiolgy lab','SOP','Standard Operating Procedure','CO-LAB-SOP-179','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reconstituton of Lyophilised Materials','SOP','Standard Operating Procedure','CO-LAB-SOP-180','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Thermomixer HC Block','SOP','Standard Operating Procedure','CO-LAB-SOP-181','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Limited Laboratory Access Procedure','SOP','Standard Operating Procedure','CO-LAB-SOP-182','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-183','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Pilot Line Blister Filling and Sealing Procedure','SOP','Standard Operating Procedure','CO-LAB-SOP-184','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-194','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-199','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-225','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-239','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Ordering of New Reagents and Chemicals','SOP','Standard Operating Procedure','CO-LAB-SOP-241','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Introduction of New microorganisms SOP','SOP','Standard Operating Procedure','CO-LAB-SOP-287','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Assessment of Potentiostat Performance','SOP','Standard Operating Procedure','CO-LAB-SOP-288','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Details of Standard Assays for use with CT-NG Project','SOP','Standard Operating Procedure','CO-LAB-SOP-289','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Running Clinical Samples in io Readers','SOP','Standard Operating Procedure','CO-LAB-SOP-290','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation of 10X and 1X TAE','SOP','Standard Operating Procedure','CO-LAB-SOP-291','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation of TSB and TSA','SOP','Standard Operating Procedure','CO-LAB-SOP-292','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-294','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Environmental Contamination Monitoring','SOP','Standard Operating Procedure','CO-LAB-SOP-295','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-LAB-SOP-296','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation of Sub-circuit cards for voltammetric detection','SOP','Standard Operating Procedure','CO-LAB-SOP-300','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation of BHI Broth ','SOP','Standard Operating Procedure','CO-LAB-SOP-301','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Preparation and use of agarose gels','SOP','Standard Operating Procedure','CO-LAB-SOP-302','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Planning for Process Validation','SOP','Standard Operating Procedure','CO-OPS-SOP-002','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Firmware Up-date','SOP','Standard Operating Procedure','CO-OPS-SOP-007','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Thermal Test Rig Set Up and Calibration','SOP','Standard Operating Procedure','CO-OPS-SOP-008','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Reader Peltier Refit procedure','SOP','Standard Operating Procedure','CO-OPS-SOP-009','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Validation of Automated Equipment and Quality System Software','SOP','Standard Operating Procedure','CO-OPS-SOP-032','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-033','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Test Method Validation','SOP','Standard Operating Procedure','CO-OPS-SOP-034','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Engineering Drawing Control','SOP','Standard Operating Procedure','CO-OPS-SOP-035','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Instrument Engineering Change Management','SOP','Standard Operating Procedure','CO-OPS-SOP-036','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-083','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-084','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-085','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-086','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-087','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-088','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-089','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-090','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-091','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-092','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-104','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-105','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-107','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-109','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-110','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-111','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-112','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-113','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-114','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-115','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-116','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-117','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-118','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-119','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-120','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-121','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-122','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-123','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-124','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-125','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-126','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-127','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-128','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-132','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-133','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-134','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-142','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Windows Software Up-date','SOP','Standard Operating Procedure','CO-OPS-SOP-165','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Pneumatics Test Rig Set Up and Calibration','SOP','Standard Operating Procedure','CO-OPS-SOP-166','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Tool Changes of the Rhychiger Heat Sealer ','SOP','Standard Operating Procedure','CO-OPS-SOP-172','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Engineering Rework Procedure ','SOP','Standard Operating Procedure','CO-OPS-SOP-174','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-186','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Force Test Rig Set Up and Calibration','SOP','Standard Operating Procedure','CO-OPS-SOP-187','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Process Validation','SOP','Standard Operating Procedure','CO-OPS-SOP-188','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-189','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-190','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-191','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Verification Testing Process SOP','SOP','Standard Operating Procedure','CO-OPS-SOP-192','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-193','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-195','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-196','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-197','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-198','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Chlamydia trachomatis and Neisseria gonorrhoeae positive daily controls','SOP','Standard Operating Procedure','CO-OPS-SOP-200','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-201','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-202','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-203','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-204','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-205','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-206','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-207','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-208','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-209','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-210','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-211','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-212','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-213','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-214','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-215','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-216','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-217','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-218','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-219','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-220','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-221','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-222','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-223','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-224','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-226','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-227','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-228','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-229','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-OPS-SOP-230','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Benchmark Roto-Therm Plus Hybridisation oven','SOP','Standard Operating Procedure','CO-PRD1-SOP-252','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use & Cleaning of the Monmouth Scientific Model Guardian 1800 Production Enclosure in Oak House','SOP','Standard Operating Procedure','CO-PRD1-SOP-254','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Mini Fuge Plus centrifuge SOP','SOP','Standard Operating Procedure','CO-PRD1-SOP-255','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Velp Scientific WIZARD IR Infared Vortex Mixer SOP','SOP','Standard Operating Procedure','CO-PRD1-SOP-256','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Standard Use of Oak House Freezers','SOP','Standard Operating Procedure','CO-PRD1-SOP-257','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Oak House N2400-3010 Magnetic Stirrer','SOP','Standard Operating Procedure','CO-PRD1-SOP-258','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Standard Use of Oak House Fridges','SOP','Standard Operating Procedure','CO-PRD1-SOP-259','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Logmore dataloggers','SOP','Standard Operating Procedure','CO-PRD1-SOP-260','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Cleaning Procedure for Oak House Production Facility','SOP','Standard Operating Procedure','CO-PRD1-SOP-261','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Entry and Exit to the Oak House Production Facility and Production Suite','SOP','Standard Operating Procedure','CO-PRD1-SOP-263','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Eupry temperarure monitoring system','SOP','Standard Operating Procedure','CO-PRD1-SOP-264','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Oak House Emergency Procedures','SOP','Standard Operating Procedure','CO-PRD1-SOP-265','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Transfer of reagent QC samples','SOP','Standard Operating Procedure','CO-PRD1-SOP-268','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Oak House Pipette Use and Calibration SOP','SOP','Standard Operating Procedure','CO-PRD1-SOP-269','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Pacplus Impulse Heat Sealer','SOP','Standard Operating Procedure','CO-PRD1-SOP-271','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Label Printing','SOP','Standard Operating Procedure','CO-PRD1-SOP-276','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Oak House Out of Hours Procedures','SOP','Standard Operating Procedure','CO-PRD1-SOP-303','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Management of Critical and Controlled Equipment at Oak House Production Facility','SOP','Standard Operating Procedure','CO-PRD1-SOP-304','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of ME2002T/00 and ML104T/00 balances in the Oak House Production Facility','SOP','Standard Operating Procedure','CO-PRD1-SOP-305','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Manufacturing Overview for the binx Cartridge Reagent Manufacturing Facility','SOP','Standard Operating Procedure','CO-PRD1-SOP-306','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of IKA Digital Roller Mixer','SOP','Standard Operating Procedure','CO-PRD1-SOP-308','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Uninterruptible Power Supply','SOP','Standard Operating Procedure','CO-PRD1-SOP-309','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of calibrated timers','SOP','Standard Operating Procedure','CO-PRD1-SOP-310','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the Rotary Vane Anemometer in Oak House','SOP','Standard Operating Procedure','CO-PRD1-SOP-311','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Guidance for the completion of Reagent Production Manufacturing Batch Records (MBRs)','SOP','Standard Operating Procedure','CO-PRD1-SOP-312','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Membrane Filters in the binx Reagent Manufacturing Facility ','SOP','Standard Operating Procedure','CO-PRD1-SOP-313','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('The use of the calibrated air temperature probe','SOP','Standard Operating Procedure','CO-PRD1-SOP-318','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Jenway 3510 model pH Meter with ATC probe and 924 30 6.0mm model Tris electrode SOP in Oak House','SOP','Standard Operating Procedure','CO-PRD1-SOP-319','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Manufacturing Overview for CT/IC Detection reagent','SOP','Standard Operating Procedure','CO-PRD1-SOP-355','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Non Conformance Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-003','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Internal Audit','SOP','Standard Operating Procedure','CO-QA-SOP-004','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Document and Records Archiving','SOP','Standard Operating Procedure','CO-QA-SOP-005','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Correction Removal and Recall Procedure ','SOP','Standard Operating Procedure','CO-QA-SOP-007','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Supplier Corrective Action Response Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-011','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Annual Quality Objectives ','SOP','Standard Operating Procedure','CO-QA-SOP-012','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Planning Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-014','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Competence of Atlas Auditors','SOP','Standard Operating Procedure','CO-QA-SOP-015','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Identification and Traceability','SOP','Standard Operating Procedure','CO-QA-SOP-016','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Sharepoint Administration','SOP','Standard Operating Procedure','CO-QA-SOP-024','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Management Review','SOP','Standard Operating Procedure','CO-QA-SOP-025','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Sharepoint','SOP','Standard Operating Procedure','CO-QA-SOP-026','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Records','SOP','Standard Operating Procedure','CO-QA-SOP-028','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Accessing and Finding Documents in QT9','SOP','Standard Operating Procedure','CO-QA-SOP-030','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Revising and Introducing Documents in QT9','SOP','Standard Operating Procedure','CO-QA-SOP-031','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Training Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-043','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Product Complaint Handling','SOP','Standard Operating Procedure','CO-QA-SOP-076','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Supplier Audit Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-077','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('CAPA Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-093','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Monitoring and Reporting of Quality Data','SOP','Standard Operating Procedure','CO-QA-SOP-096','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Document Matrix','SOP','Standard Operating Procedure','CO-QA-SOP-098','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Deviation procedure','SOP','Standard Operating Procedure','CO-QA-SOP-099','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Change Management','SOP','Standard Operating Procedure','CO-QA-SOP-139','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Document Control & Control of Quality Records','SOP','Standard Operating Procedure','CO-QA-SOP-140','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Managing an External Regulatory Visit','SOP','Standard Operating Procedure','CO-QA-SOP-147','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QT9 - Periodic Review and Making Documents Obsolete','SOP','Standard Operating Procedure','CO-QA-SOP-237','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QT9 Administration','SOP','Standard Operating Procedure','CO-QA-SOP-244','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Post Market Surveillance','SOP','Standard Operating Procedure','CO-QA-SOP-267','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Applicable Standards Management Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-274','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Product Risk Management ','SOP','Standard Operating Procedure','CO-QA-SOP-283','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('FMEA Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-284','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Hazard Analysis Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-285','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Vigilance and Medical Reporting Procedure','SOP','Standard Operating Procedure','CO-QA-SOP-326','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Tools for Root Cause Analysis','SOP','Standard Operating Procedure','CO-QA-SOP-345','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('EU Regulatory Strategy and Process','SOP','Standard Operating Procedure','CO-QA-SOP-356','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('EU Performance Evaluation','SOP','Standard Operating Procedure','CO-QA-SOP-357','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Control Out of Specification Results Procedure','SOP','Standard Operating Procedure','CO-QC-SOP-012','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of Stuart SRT6D Roller Mixer','SOP','Standard Operating Procedure','CO-QC-SOP-021','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procedure to control chemical and biological spillages','SOP','Standard Operating Procedure','CO-QC-SOP-094','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QC Laboratory Cleaning SOP','SOP','Standard Operating Procedure','CO-QC-SOP-154','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Quality Control Rounding procedure','SOP','Standard Operating Procedure','CO-QC-SOP-171','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Laboratory Investigation Procedure','SOP','Standard Operating Procedure','CO-QC-SOP-173','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Use of the SB3 Rotator','SOP','Standard Operating Procedure','CO-QC-SOP-185','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('QC Sample Handling and Retention Procedure','SOP','Standard Operating Procedure','CO-QC-SOP-282','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procedure for io Release','SOP','Standard Operating Procedure','CO-QC-SOP-286','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('dPCR quantification of CT & NG Vircell inputs','SOP','Standard Operating Procedure','CO-QC-SOP-293','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('#N/A','SOP','Standard Operating Procedure','CO-QC-SOP-299','#N/A');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Control of Marketing and Promotion','SOP','Standard Operating Procedure','CO-SAM-SOP-009','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procedure for Commercial Storage and Distribution','SOP','Standard Operating Procedure','CO-SUP-SOP-001','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Intrument service and repair','SOP','Standard Operating Procedure','CO-SUP-SOP-002','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procudure for inventory control and IBP ','SOP','Standard Operating Procedure','CO-SUP-SOP-003','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('New customer procedure','SOP','Standard Operating Procedure','CO-SUP-SOP-005','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Equipment and fulfilment and field visits','SOP','Standard Operating Procedure','CO-SUP-SOP-006','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Procedure for Sales Administration& Order Handling','SOP','Standard Operating Procedure','CO-SUP-SOP-007','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Customer Returns','SOP','Standard Operating Procedure','CO-SUP-SOP-013','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('quality Control','SOP','Standard Operating Procedure','CO-SUP-SOP-025','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Complete QC Inspections','SOP','Standard Operating Procedure','CO-SUP-SOP-037','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Change of Stock (QC release)','SOP','Standard Operating Procedure','CO-SUP-SOP-038','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Manage Quality Codes','SOP','Standard Operating Procedure','CO-SUP-SOP-039','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('New Customer Set-Up','SOP','Standard Operating Procedure','CO-SUP-SOP-040','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Customer Sales Contracts','SOP','Standard Operating Procedure','CO-SUP-SOP-041','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Enter & Release Sales Orders','SOP','Standard Operating Procedure','CO-SUP-SOP-042','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Mark Sales Orders as Despatched','SOP','Standard Operating Procedure','CO-SUP-SOP-043','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Invoice Customers Manually','SOP','Standard Operating Procedure','CO-SUP-SOP-044','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Cutomer Price Lists','SOP','Standard Operating Procedure','CO-SUP-SOP-045','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Create New Customer Return','SOP','Standard Operating Procedure','CO-SUP-SOP-046','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Transfer Order','SOP','Standard Operating Procedure','CO-SUP-SOP-047','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Raise PO Non Stock and Services','SOP','Standard Operating Procedure','CO-SUP-SOP-048','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Receive non sock PO ','SOP','Standard Operating Procedure','CO-SUP-SOP-049','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Raise PO - Stock Item','SOP','Standard Operating Procedure','CO-SUP-SOP-050','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Receive Stock Purchase Orders','SOP','Standard Operating Procedure','CO-SUP-SOP-051','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('New Supplier Set-Up','SOP','Standard Operating Procedure','CO-SUP-SOP-052','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Raise and Release PO','SOP','Standard Operating Procedure','CO-SUP-SOP-053','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Complete PO','SOP','Standard Operating Procedure','CO-SUP-SOP-054','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Goods Movement ','SOP','Standard Operating Procedure','CO-SUP-SOP-055','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Check Sales Order due Date','SOP','Standard Operating Procedure','CO-SUP-SOP-056','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Consume to cost centre or Project ','SOP','Standard Operating Procedure','CO-SUP-SOP-057','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Inspection Plans','SOP','Standard Operating Procedure','CO-SUP-SOP-058','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Credit Customer Returns','SOP','Standard Operating Procedure','CO-SUP-SOP-059','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Customer Returns','SOP','Standard Operating Procedure','CO-SUP-SOP-060','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('New Project Set-Up','SOP','Standard Operating Procedure','CO-SUP-SOP-061','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Add Team Member to a Task','SOP','Standard Operating Procedure','CO-SUP-SOP-062','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Book Time Against A Project','SOP','Standard Operating Procedure','CO-SUP-SOP-063','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Create a PO Within a Project','SOP','Standard Operating Procedure','CO-SUP-SOP-064','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Complete a timesheet','SOP','Standard Operating Procedure','CO-SUP-SOP-065','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Manager Approvals App','SOP','Standard Operating Procedure','CO-SUP-SOP-066','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Managing Expired Identified Stock','SOP','Standard Operating Procedure','CO-SUP-SOP-067','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Purchasing SOP','SOP','Standard Operating Procedure','CO-SUP-SOP-068','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Supplier Evaluation SOP','SOP','Standard Operating Procedure','CO-SUP-SOP-069','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values (' Supplier Risk Assessment  Approval and Monitoring Procedure ','SOP','Standard Operating Procedure','CO-SUP-SOP-070','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values (' Instructions for receipt of incoming Non-Stock goods  assigning GRN numbers and labelling ','SOP','Standard Operating Procedure','CO-SUP-SOP-072','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Standard Cost Roll Up','SOP','Standard Operating Procedure','CO-SUP-SOP-073','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('UK Stock Procurement & Movements (Supply Chain)','SOP','Standard Operating Procedure','CO-SUP-SOP-074','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Order to Cash','SOP','Standard Operating Procedure','CO-SUP-SOP-075','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('New Items','SOP','Standard Operating Procedure','CO-SUP-SOP-231','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values (' Instructions for receipt of incoming Non-Stock goods  assigning GRN numbers and labelling ','SOP','Standard Operating Procedure','CO-SUP-SOP-277','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Pilot Line Electronic Stock Control','SOP','Standard Operating Procedure','CO-SUP-SOP-278','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Stock take procedure','SOP','Standard Operating Procedure','CO-SUP-SOP-279','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Setting Expiry Dates for Incoming Materials','SOP','Standard Operating Procedure','CO-SUP-SOP-280','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Cartridge Component Stock Control Procedure','SOP','Standard Operating Procedure','CO-SUP-SOP-281','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Oak House Supply Chain Reagent Production Process','SOP','Standard Operating Procedure','CO-SUP-SOP-320','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Incoming Goods Procedure for deliveries into Oak House Manufacturing Site','SOP','Standard Operating Procedure','CO-SUP-SOP-321','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Supply Team Oak House Operations','SOP','Standard Operating Procedure','CO-SUP-SOP-322','HIGH');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Demand Planning','SOP','Standard Operating Procedure','CO-SUP-SOP-323','LOW');
Insert into documents (documentname,DocumentCode,DocumentType,DocumentNumber,RiskLevel) values ('Packaging and Shipping procedure for binx Cartridge Reagent','SOP','Standard Operating Procedure','CO-SUP-SOP-324','HIGH');